IB-22 store 생성 도메인 개발
Inforigina/irg-api-server pull request #25
Opened 2022-09-14 14:09 UTC by jinsy731

2022-09-14 14:55 UTC, dlwlstks96 approved these changes

2022-09-14 15:22 UTC, goyounha11 requested changes
사업자등록번호는 유니크키를 줘야하지않나 싶습니다.

2022-09-15 01:55 UTC, jinsy731 commented
> 사업자등록번호는 유니크키를 줘야하지않나 싶습니다.

2022-09-15 02:21 UTC, goyounha11 approved these changes

2022-09-15 02:48 UTC, merged